PubMatic-OpenWrap/prebid-server

- endpoints/openrtb2/ctv/impressions.go
- endpoints/openrtb2/ctv/impressions_test.go
- endpoints/openrtb2/ctv_auction.go
@pm-viral-vala please review the code review changes. Also added info level logs and moved test cases to table-driven test structure
> UOE-5066: Code review changes

- adapters/appnexus/appnexus.go
Reverts PubMatic-OpenWrap/prebid-server#50
> Revert "fix UOE-5123 (cat missing appnexus)"

- openrtb_ext/adpod.go
> OTT-8, UOE-5367: adpod validation fix

- openrtb_ext/adpod.go
> OTT-13: update adpod validations

- main.go
This  required for mocking PBS response
> OTT-18: Populating deal prioritisation specific keys

- endpoints/events/vtrack.go
- endpoints/events/vtrack_test.go
Added support for forming and injecting video start event VAST XML
@pm-viral-vala : please do the code review and approve
> OTT-180: Added support for forming and injecting video start event

- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
@pm-viral-vala  please review and approve
> OTT-183: Fixed the issue of operId=8 must be first query param

- endpoints/events/vtrack.go
- endpoints/events/vtrack_test.go
OTT-192: Ensure sURL (Event Tracker) and orig (OW Logger) parameter values are consistent
> OTT-192: Ensure sURL (Event Tracker) and orig (OW Logger) parameter values are consistent

- exchange/bidder.go
- openrtb_ext/response.go
Added temporary change for enable QA to debug and verify the changes for OTT-159
> OTT-205: (Temporary for QA) ext.params to show impIndex and VastTagindex

- endpoints/events/vtrack.go
- endpoints/events/vtrack_test.go
- exchange/bidder.go
- exchange/events.go
- exchange/events_test.go
- exchange/exchange.go
OTT-197: Log Partner bidder code in video event tracker
> OTT-197: Log Partner bidder code in video event tracker

- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
> OTT-161 : filter vast tags based on duration

- exchange/bidder.go
> OTT-214 : Fix panic while getting debug info http calls

- adapters/vastbidder/bidder_macro.go
> OTT-232 : Fix incorrect tagID in final VastTag URLs

- adapters/vastbidder/vast_tag_response_handler.go
- errortypes/code.go
- errortypes/errortypes.go
> OTT-233 : Fix error code for VAST bidders when bid price is zero

- exchange/exchange.go
- exchange/exchange_test.go
1) Skip dedupe check
2) Collision detector
> OTT-216: add all SupportDeal features

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatictest/supplemental/app.json
- openrtb_ext/imp.go
(cherry picked from commit b77c08216f6d1c1d6f39770a8be5823a0edc68e5)
> UOE-7297: Place skadn at bidreq.imp[].ext.skadn #237

- .github/CODEOWNERS
- .github/pull_request_template.md
TODO: Add mandatory approval from code owners
> Add default pull request template

- main_test.go
- router/router.go
> UOE-7300: Fix Github pipeline

- main_test.go
- router/router.go
Reverts PubMatic-OpenWrap/prebid-server#252
> Revert "UOE-7300: Fix Github pipeline"

- adapters/bidder.go
- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- exchange/bidder.go
> UOE-7051: Fix pubmatic aliases buyid targeting key

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- adapters/pubmatic/pubmatictest/exemplary/banner.json
- adapters/pubmatic/pubmatictest/exemplary/video-rewarded.json
- adapters/pubmatic/pubmatictest/exemplary/video.json
- adapters/pubmatic/pubmatictest/params/race/banner.json
- adapters/pubmatic/pubmatictest/params/race/video.json
- adapters/pubmatic/pubmatictest/supplemental/app.json
- openrtb_ext/imp_pubmatic.go
- static/bidder-params/pubmatic.json
> UOE-7270: Support kadfloor param in PubMatic adptr

- config/config.go
- config/config_test.go
- openrtb_ext/request.go
Added New floor structure in Prebid extension
Added new configs to enable floor pricing
> OTT-509::Addded new price floor configs and floor structure

- gdpr/vendorlist-fetching.go
- gdpr/vendorlist-scheduler_test.go
> UOE-7728: Fix cacheSave and Load func(). Add tests

- endpoints/events/vtrack_ow.go
- endpoints/events/vtrack_ow_test.go
- endpoints/openrtb2/ctv/types/adpod_types.go
- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
- exchange/events.go
- exchange/exchange.go
Added changes for using generated bid ID
> OTT-297: Added changes for using generated bid ID

- exchange/floors_test.go
Fixed UT for floors enforcement
> OTT-478: Fixed UT for floors enforcement

- config/accounts.go
- config/accounts_test.go
- exchange/bidder.go
- exchange/bidder_test.go
- exchange/bidder_validate_bids.go
- exchange/bidder_validate_bids_test.go
- exchange/exchange.go
- exchange/exchange_test.go
> Validate extra-bidder #2257 #2174

- exchange/exchange.go
- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
- floors/floors_test.go
- openrtb_ext/floors.go
> OTT-583 :: Refactored floor code and used RequestWrapper for retrieving and setting extension object

- floors/floors_test.go
> Import path updated

- exchange/exchange.go
- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/floors.go
- floors/floors_test.go
- floors/validate.go
- floors/validate_test.go
- openrtb_ext/floors.go
Updated for currency conversion validation
Added validation for SkipRate at data level and root level in floor json 
Added currency details in floor rejection errors
> OTT-479: Updated for currency conversion related validation and error in rejected bids

- exchange/floors.go
> OTT-596: Updated error message for currency conversion error

- exchange/floors_test.go
> OTT-596: Fixed UT's for  error message for currency conversion error

- floors/floors.go
> OTT-598:: Added check if floor data is nil

- floors/floors.go
- floors/validate.go
- floors/validate_test.go
- openrtb_ext/floors.go
> OTT-479:: Renamed function and fixed formatting issue

- endpoints/cookie_sync.go
- endpoints/cookie_sync_test.go
PBS config needed to test this:
```
gdpr:
enabled: true
default_value: true
host_vendor_id: 76
timeouts_ms:
init_vendorlist_fetches: 100000
active_vendorlist_fetch: 100000
```
> UOE-7905: Do not allow publishers to bypass GDPR

- endpoints/cookie_sync.go
- endpoints/cookie_sync_test.go
> UOE-7905: Do not allow publishers to bypass GDPR (#326)

- endpoints/cookie_sync.go
- endpoints/cookie_sync_test.go
> Release: OWS_Q2_19_July_2022

- exchange/exchange.go
- exchange/price_granularity.go
- exchange/price_granularity_test.go
- openrtb_ext/request.go
> OTT-603: adding new test price granularity

- openrtb_ext/request.go
> OTT-641: adding test flag for price granularity

- floors/floors_test.go
- floors/rule.go
- openrtb_ext/floors.go
> OTT-652: Added changes for reading adunit from imp.tagID

- floors/floors_test.go
- floors/rule.go
- openrtb_ext/floors.go
- openrtb_ext/user.go
> Release: OWS_Q3_13_September_2022

- config/config.go
- config/config_ow.go
> refactor OW config and prometheus patch

- exchange/exchange.go
- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
- floors/floors_test.go
- floors/rule.go
- floors/rule_test.go
- floors/validate.go
- floors/validate_test.go
- openrtb_ext/floors.go
Incorporating Review Comments of https://github.com/prebid/prebid-server/pull/2341 into PubMatic PrebidServer fork.
> OTT-656: Changes for addressing review comments on PR raised to merge changes in prebid master branch

- adapters/pubmatic/pubmatictest/supplemental/eid.json
- go.mod
Adding test cases for user.ext.eid to user.eid for adapter behaviour verification
> UOE-8097:Added Testcases for user.ext.eid to user.eid changes

- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/floors.go
- floors/rule.go
- go.sum
> OTT-737: Floors enabled flag should be considered at true by default, if req.ext.prebid.floors is not provided in request

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
> UOE-8247: bug fix for amp targeting

- exchange/exchange.go
- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
- floors/rule.go
- floors/rule_test.go
- floors/validate.go
- floors/validate_test.go
> OTT-744: Updated enforceFloors() for enforcement based on enforcepbs flag

- config/config_test.go
> OTT-698 :: Unit test cases updated

- config/config.go
> OTT-698 :: Modified MaxInt according to go version 16

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
> UOE-8257: bug fix (trim keys)for amp targeting

- exchange/exchange.go
- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
- floors/rule.go
- floors/rule_test.go
- floors/validate.go
- floors/validate_test.go
> OTT-744: Updated enforceFloors() for enforcement based on enforcepbs flag (#373)

- exchange/exchange_test.go
- exchange/exchangetest/floors-bid-ext.json
- exchange/floors.go
- exchange/floors_test.go
- exchange/utils.go
- floors/floors.go
- floors/floors_test.go
- floors/rule.go
- floors/rule_test.go
- openrtb_ext/imp.go
> UOE-8485: Use Prebid's way to update imp ext

- analytics/config/config_ow.go
- analytics/config/config_ow_test.go
- analytics/config/config_test.go
- analytics/core.go
- analytics/filesystem/file_module_test.go
- analytics/pubstack/helpers/json_test.go
- analytics/pubstack/pubstack_module_test.go
- config/config.go
- endpoints/openrtb2/amp_auction_test.go
- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/video_auction_test.go
- exchange/exchange.go
- main.go
- main_test.go
- router/router_ow.go
- router/router_ow_test.go
Kindly check the review comments from https://github.com/PubMatic-OpenWrap/prebid-server/pull/393/files
> OTT-783: Basic design changes for pubmatic analytic module to log rejection bid scenarios

- analytics/config/config_ow.go
- analytics/config/config_ow_test.go
- analytics/config/config_test.go
- analytics/core.go
- analytics/core_ow.go
- analytics/filesystem/file_module_test.go
- analytics/pubstack/helpers/json_test.go
- analytics/pubstack/pubstack_module_test.go
- config/config.go
- endpoints/openrtb2/amp_auction.go
- endpoints/openrtb2/amp_auction_test.go
- endpoints/openrtb2/auction.go
- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/video_auction.go
- endpoints/openrtb2/video_auction_test.go
- exchange/exchange.go
- router/router_ow.go
- router/router_ow_test.go
> OTT-776:  (OTT-783) Basic design changes for pubmatic analytic module to log rejection bid scenarios

- config/config.go
- exchange/floors.go
- floors/fetcher.go
- floors/floors.go
- floors/floors_test.go
> OTT-773 :: Added code to read Fetch URL from floor.location.url

- adapters/infoawarebidder_ow_test.go
> UOE-7803: fix code coverage calculation for PBS fork

- floors/floors_test.go
- floors/rule.go
- floors/rule_test.go
- openrtb_ext/floors.go
…pecifications from prebid PRD
> OTT-810: As a prebid server user, implement recently updated floors specifications from prebid PRD

- floors/floors.go
> OTT-810: Updated req.ext.prebid.floors after updating Skipped flag

- openrtb_ext/imp.go
> OTT-818 :: Added floorMin and floorMinCur in imp extension

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- openrtb_ext/imp_pubmatic.go
> Release: OpenWrap_Q1_25-Jan-23

- floors/fetcher.go
- floors/floors.go
- floors/validate.go
- openrtb_ext/floors.go
> OTT-942 : Added code for deep copy of modelgroup before validating rule keys

- floors/floors.go
- floors/floors_test.go
- floors/validate_test.go
> OTT-934 : Deep copy modelgroup while preparing floors from fetched and request

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatictest/supplemental/multiformat.json
> UOE-8831 Adding changes for native support

- exchange/floors.go
- exchange/floors_test.go
- floors/enforce.go
- floors/enforce_test.go
- floors/fetcher.go
- floors/fetcher_test.go
> OTT-979 :: Refactor Floor code

- endpoints/openrtb2/auction.go
- endpoints/openrtb2/ctv/constant/constant.go
- endpoints/openrtb2/ctv_auction.go
Reverts PubMatic-OpenWrap/prebid-server#466
> Revert "OTT-970: As a OpenWrap Server user, should be able to pass VAST unwra…"

- exchange/exchangetest/floors-bid-ext.json
- exchange/floors.go
- exchange/floors_test.go
- router/router_ow.go
- router/router_ow_test.go
> Openwrap_release_9th_may_2023

- endpoints/openrtb2/amp_auction.go
- endpoints/openrtb2/auction.go
- endpoints/openrtb2/ctv_auction.go
- exchange/exchange.go
- exchange/exchange_ow.go
- exchange/exchange_ow_test.go
- metrics/config/metrics.go
- metrics/go_metrics_ow.go
- metrics/metrics.go
- metrics/metrics_mock_ow.go
- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_ow.go
- metrics/prometheus/prometheus_ow_test.go
> OTT-1058: record number of deal responses for given pub-prof-partner

- floors/floors.go
- floors/floors_test.go
> OTT-1077 :: Fixed floor location value when floor data is nil

- exchange/bidder.go
- exchange/exchange_ow.go
- metrics/pubmatic_stats/stats.go
- metrics/pubmatic_stats/stats_test.go
> Update ci with latest master

- exchange/exchange.go
- exchange/exchange_ow.go
- exchange/exchange_ow_test.go
- metrics/config/metrics.go
- metrics/go_metrics_ow.go
- metrics/metrics.go
- metrics/metrics_mock_ow.go
- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_ow.go
- metrics/prometheus/prometheus_ow_test.go
> OTT-1084: Adding stats for counting vastVersion labelled by bidder and vastVersion

- exchange/exchange.go
>  OTT-1066: Fixed config parameter name for bid adjustment factor

- adapters/adbuttler/adbuttler.go
- adapters/adbuttler/adbuttler_request.go
- adapters/adbuttler/adbuttler_response.go
- adapters/adbuttler/constant.go
- adapters/koddi/koddi.go
- config/adapter.go
- config/adapter_cm.go
- config/config.go
- endpoints/openrtb2/auction.go
- exchange/adapter_builders.go
- exchange/utils.go
- openrtb_ext/bidders.go
- openrtb_ext/imp_commerce.go
- openrtb_ext/request.go
- router/router_ow.go
- static/bidder-info/adbuttler.yaml
- static/bidder-info/koddi.yaml
- static/bidder-params/adbuttler.json
- static/bidder-params/koddi.json
> PR to Merge Ci-Commerce-Media to Master-Commerce-Media

- endpoints/openrtb2/ctv_auction.go
- floors/enforce.go
- floors/enforce_test.go
> UOE-9156: Fix for price granularity and redundant floor errors

- router/router.go
> UOE-9292: restore httpclient dial timeout w.r.t #511

- floors/enforce_test.go
- floors/fetcher.go
- floors/fetcher_test.go
- floors/floors.go
- floors/floors_test.go
- openrtb_ext/floors.go
> OTT-1074 :: Introduced data rate to select source of floors

- floors/floors_test.go
> Fixed import issue

- modules/pubmatic/vastunwrap/module.go
> Updated traffic percentage key in the json config

- modules/pubmatic/vastunwrap/module.go
> Updated json key name of VastUnwrapModule struct

- go.mod
- go.sum
- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/module.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/stats/metrics.go
- modules/pubmatic/vastunwrap/stats/metrics_test.go
- modules/pubmatic/vastunwrap/unwrap_service.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-1146: Added code to update vast unwrap status in the prometheus stats

- modules/pubmatic/openwrap/cache/gocache/gocache.go
> UOE-9178: add missing slot regex key format

- scripts/coverage.sh
> UOE-8799: temporarily skip openwrap module coverage

- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/stats/metrics.go
- modules/pubmatic/vastunwrap/stats/metrics_test.go
- modules/pubmatic/vastunwrap/stats/mock/mock.go
- modules/pubmatic/vastunwrap/unwrap_service.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-1192: Log wrapper count for vast unwrap request and update existing vast unwrap stat

- exchange/exchange_ow_test.go
- exchange/exchange_test.go
- metrics/config/metrics.go
- metrics/config/metrics_ow.go
- metrics/config/metrics_ow_test.go
- metrics/config/metrics_test.go
- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_test.go
- modules/moduledeps/deps.go
- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/bidderparams/pubmatic.go
- modules/pubmatic/openwrap/defaultbids.go
- modules/pubmatic/openwrap/entrypointhook.go
- modules/pubmatic/openwrap/metrics/config/metrics.go
- modules/pubmatic/openwrap/metrics/config/metrics_test.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_test.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats_test.go
- modules/pubmatic/openwrap/models/constants.go
- modules/pubmatic/openwrap/module.go
- modules/pubmatic/openwrap/openwrap.go
- router/router.go
Please refer - https://github.com/PubMatic-OpenWrap/prebid-server/pull/526  for review comments
> OTT-1160: Introduce prometheus metric-engine in openwrap module

- modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
- modules/pubmatic/openwrap/cache/gocache/fsc_test.go
- modules/pubmatic/openwrap/cache/gocache/gocache_test.go
- modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
- modules/pubmatic/openwrap/cache/gocache/slot_mappings_test.go
- modules/pubmatic/openwrap/cache/gocache/sync_test.go
- modules/pubmatic/openwrap/cache/gocache/util.go
- modules/pubmatic/openwrap/cache/gocache/util_test.go
- modules/pubmatic/openwrap/cache/gocache/vast_tags_test.go
> UOE-9179: fix import statements in OpenWrap cache package

- modules/pubmatic/openwrap/cache/gocache/adunit_config.go
- modules/pubmatic/openwrap/cache/gocache/fsc.go
- modules/pubmatic/openwrap/cache/gocache/partner_config.go
- modules/pubmatic/openwrap/cache/gocache/slot_mappings.go
- modules/pubmatic/openwrap/cache/gocache/vast_tags.go
> UOE-9179: openwrap cache, return all errors

- Makefile
- modules/pubmatic/openwrap/cache/cache.go
- modules/pubmatic/openwrap/cache/gocache/tracking_beacon_first.go
- modules/pubmatic/openwrap/cache/gocache/tracking_beacon_first_test.go
- modules/pubmatic/openwrap/cache/mock/mock.go
- modules/pubmatic/openwrap/config/config.go
- modules/pubmatic/openwrap/database/database.go
- modules/pubmatic/openwrap/database/mock/mock.go
- modules/pubmatic/openwrap/database/mock_driver/mock.go
- modules/pubmatic/openwrap/database/mysql/tracking_beacon_first.go
- modules/pubmatic/openwrap/database/mysql/tracking_beacon_first_test.go
- modules/pubmatic/openwrap/tbf/tbf.go
- modules/pubmatic/openwrap/tbf/tbf_test.go
> OTT-1225: Tracking-Beacon-First (TBF) for banner creatives

- adapters/bidder.go
- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- exchange/exchange.go
- exchange/utils.go
- exchange/utils_ow.go
- exchange/utils_ow_test.go
- exchange/utils_test.go
> OTT-1176:  Apply BidAdjustment to imp.BidFloor

- floors/floors.go
- floors/floors_test.go
- modules/pubmatic/openwrap/tbf/tbf.go
> OTT-1195 :: Always update fetchStatus with dynamic fetch status

- Makefile
- modules/pubmatic/openwrap/cache/gocache/fsc_test.go
- modules/pubmatic/openwrap/cache/gocache/gocache_test.go
- modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
- modules/pubmatic/openwrap/entrypointhook_test.go
- modules/pubmatic/openwrap/metrics/config/metrics.go
- modules/pubmatic/openwrap/metrics/config/metrics_test.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/metrics_sshb.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb_test.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_test.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
- modules/pubmatic/openwrap/tbf/tbf.go
- modules/pubmatic/openwrap/util_test.go
> UOE-9434: migrate sshb metrics to pbs-ow module

- modules/pubmatic/openwrap/metrics/config/metrics.go
- modules/pubmatic/openwrap/metrics/config/metrics_test.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb_test.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
> OTT-1276: Introduce Prometheus stats for req.Device.Geo.Country

- modules/pubmatic/openwrap/cache/gocache/gocache.go
- modules/pubmatic/openwrap/cache/gocache/partner_config.go
- modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
- modules/pubmatic/openwrap/database/mysql/adunit_config.go
- modules/pubmatic/openwrap/database/mysql/adunit_config_test.go
> OTT-1297: cache fix: populate cache only upon successful DB calls

- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
- modules/pubmatic/openwrap/cache/gocache/gocache.go
- modules/pubmatic/openwrap/cache/gocache/partner_config.go
- modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
- modules/pubmatic/openwrap/database/mysql/adunit_config.go
- modules/pubmatic/openwrap/database/mysql/adunit_config_test.go
- modules/pubmatic/openwrap/metrics/config/metrics.go
- modules/pubmatic/openwrap/metrics/config/metrics_test.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_sshb_test.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
> Release OpenWrap_Q4_04-Oct-23

- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
> Fix Panic hook: prometheus singleton

- exchange/exchange.go
- metrics/prometheus/prometheus_test.go
> OTT-1305: add prometheus stats for floors requests

- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-734: Fixed UT's

- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/vastunwrap/module_test.go
> OTT-734: Fixed UT and corrected import statement

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatictest/exemplary/fledge.json
> IDNT-854: pubmatic: add fledge support (#3174)

- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-734: Fixed UT

- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-734: go fmt  fix

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatictest/exemplary/fledge.json
- modules/pubmatic/openwrap/metrics/stats/client.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
This PR downmerge master into ci
Ignores the code coverage of models pacakge
> Ignore code coverage of openwrap/models package

- .github/workflows/adapter-code-coverage.yml
- .github/workflows/cross-repo-issue.yml
> OTT-1409: fix github actions: adapter code coverage

- modules/pubmatic/openwrap/cache/gocache/adunit_config_test.go
- modules/pubmatic/openwrap/cache/gocache/fullscreenclickability_test.go
- modules/pubmatic/openwrap/cache/gocache/gocache.go
- modules/pubmatic/openwrap/cache/gocache/gocache_test.go
- modules/pubmatic/openwrap/cache/gocache/partner_config_test.go
- modules/pubmatic/openwrap/cache/gocache/slot_mappings_test.go
- modules/pubmatic/openwrap/cache/gocache/sync_test.go
- modules/pubmatic/openwrap/cache/gocache/vast_tags_test.go
- modules/pubmatic/openwrap/config/config.go
- modules/pubmatic/openwrap/openwrap.go
> UOE-9673: revert dbcache rename

- modules/pubmatic/openwrap/targeting.go
> OTT-1402: fix winner targeting

- modules/pubmatic/openwrap/floors.go
- modules/pubmatic/openwrap/floors_test.go
> OTT-1360: As OpenWrap user, disable dynamic fetch if floors module disabled from UI for all S2S profiles

- adapters/criteoretail/criteoretail_mockresponse.go
- adapters/criteoretail/criteoretail_response.go
> Ci commerce media

- adapters/adbuttler/adbuttler_response.go
- errortypes/code.go
- errortypes/errortypes.go
- go.mod
Jira : https://inside.pubmatic.com:9443/jira/browse/COMM-1028
> Comm-1028 mandatory fields check added

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/entrypointhook.go
- modules/pubmatic/openwrap/models/nbr/codes.go
- modules/pubmatic/openwrap/util.go
- modules/pubmatic/openwrap/util_test.go
> OTT-1418: fix NBR code sequence

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/models/nbr/codes.go
- modules/pubmatic/openwrap/util.go
> UOE-9681: mapping not uploaded nbr

- modules/pubmatic/openwrap/auctionresponsehook.go
- modules/pubmatic/openwrap/models/openwrap.go
- modules/pubmatic/openwrap/tracker/create.go
> UOE-9681: fix eg, en multicurrency case

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
> UOE-9681: fix prebid validation in ow module

- modules/pubmatic/vastunwrap/entryhook.go
- modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/models/request.go
- modules/pubmatic/vastunwrap/module.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/stats/metrics.go
- modules/pubmatic/vastunwrap/stats/metrics_test.go
- modules/pubmatic/vastunwrap/stats/mock/mock.go
- modules/pubmatic/vastunwrap/unwrap_service.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
Reverts PubMatic-OpenWrap/prebid-server#647
> Revert "OTT-1431: Added publisher level stats for vast-wrapper count and response time"

- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/stats/metrics.go
- modules/pubmatic/vastunwrap/stats/metrics_test.go
- modules/pubmatic/vastunwrap/stats/mock/mock.go
- modules/pubmatic/vastunwrap/unwrap_service.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-1491: Added response time stats at wrapper count level

- modules/pubmatic/openwrap/allprocessedbidresponsehook.go
- modules/pubmatic/openwrap/allprocessedbidresponsehook_test.go
- modules/pubmatic/openwrap/processedauctionhook.go
- modules/pubmatic/openwrap/processedauctionhook_test.go
> UOE-9681: Fix-bidID for non module requests

- modules/pubmatic/openwrap/allprocessedbidresponsehook.go
- modules/pubmatic/openwrap/allprocessedbidresponsehook_test.go
- modules/pubmatic/openwrap/processedauctionhook.go
- modules/pubmatic/openwrap/processedauctionhook_test.go
> Release 9th Jan Fix

- modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
> OTT-1568: Fix concurrent map write issue

- adapters/adbuttler/adbuttler_request.go
- adapters/adbuttler/constant.go
> subcategory validation added

- modules/pubmatic/openwrap/auctionresponsehook.go
> OTT-1585: Dur is missing in logger for test request.

- modules/pubmatic/openwrap/adunitconfig/utils.go
> OTT-1559: Transparency object is not getting passed in prebid modules

- modules/pubmatic/openwrap/auctionresponsehook_test.go
> UOE-9863: Test cases for AuctionResponseHook

- modules/pubmatic/openwrap/auctionresponsehook.go
- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/middleware/adpod/adpod.go
- modules/pubmatic/openwrap/middleware/adpod/json.go
- modules/pubmatic/openwrap/models/openwrap.go
- modules/pubmatic/openwrap/models/request.go
- openrtb_ext/response.go
> Adding changes for Inline HB - Redirect for POST & GET

- go.mod
- go.sum
> OTT-1564: support vastunwrap for in-app profiles

- config/account.go
- exchange/exchange.go
- exchange/exchange_ow.go
- exchange/non_bid_reason.go
- metrics/prometheus/prometheus.go
> UOE-10268: cap bid price

- floors/floors_test.go
- floors/validate.go
- floors/validate_test.go
- openrtb_ext/floors.go
> OTT-1706: Changed datatype of FloorsSchemaVersion from string to int

- analytics/build/build.go
> OTT-1732: fix: pubmatic logger not initialised

- modules/pubmatic/openwrap/endpoints/legacy/openrtb/v25/video.go
> OTT-1732: Updated import path

- .github/workflows/validate.yml
> enabled ./validate check for ci branch

- analytics/pubmatic/logger.go
- analytics/pubmatic/logger_test.go
> OTT-1248: Use updated floor value using floor rules  into logger in case of No bid case

- modules/pubmatic/openwrap/tracker/video.go
- modules/pubmatic/openwrap/tracker/video_test.go
> OTT-1800: Export functions for adding Pricing Model in VAST XML

- modules/pubmatic/openwrap/endpoints/legacy/ctv/constant.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation_test.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/util.go
> OTT-1886: Drop the EID object if the ID value is empty, to avoid bad requests

- floors/floors.go
- floors/floors_test.go
> OTT-1905: Consider floorMin value while comparing with imp.bidfloor

- exchange/bidder.go
- exchange/bidder_test.go
- exchange/exchange.go
- exchange/exchange_test.go
- exchange/non_bid_reason.go
- exchange/seat_non_bids.go
- stored_requests/data/by_id/accounts/test.json
> Fixed the multiple seatnonbid objects per seat

- endpoints/openrtb2/auction_ow_test.go
TestUpdateResponseExtOW ut failing intermetiently due to map used for create owlogger
> Unit test fix : TestUpdateResponseExtOW

- modules/pubmatic/openwrap/models/tracking.go
- modules/pubmatic/openwrap/models/utils_test.go
- modules/pubmatic/openwrap/tracker/create.go
- modules/pubmatic/openwrap/tracker/create_test.go
- modules/pubmatic/openwrap/tracker/tracker.go
>  OTT-1920: Added floor provider in tracker

- modules/pubmatic/openwrap/metrics/config/multimetrics.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
> UOE-10554-P1 adding bc and pn mismatch stats

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/parser_implementation_test.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/util.go
- modules/pubmatic/openwrap/endpoints/legacy/ctv/util_test.go
> OTT-1948: Validate and update user EIDs with valid values

- exchange/bidder.go
- exchange/bidder_test.go
- exchange/exchange.go
- exchange/seat_non_bids.go
- exchange/seat_non_bids_test.go
- Verified SeatNonBids generated due to Floor
- Verified SeatNonBids generated due to bidder-unreachable
- Verified No SeatNonBids flow
> Rename seatNonBids to seatNonBidBuilder

- exchange/exchange.go
> OTT-1824-P1: enabling fastxml for vcr

- endpoints/events/test/vast.txt
- endpoints/events/vtrack_ow.go
- endpoints/events/vtrack_ow_test.go
- exchange/events_ow.go
- exchange/exchange_ow.go
- exchange/exchange_ow_test.go
- metrics/config/metrics_ow.go
- metrics/go_metrics_ow.go
- metrics/metrics_mock_ow.go
- metrics/metrics_ow.go
- metrics/prometheus/prometheus_ow.go
- metrics/prometheus/prometheus_ow_test.go
> OTT-1824-P2 removing bidder key and updating logs for fastxml

- endpoints/events/vtrack_ow_test.go
> OTT-1824-Fix-Imports

- adapters/vastbidder/etree_parser.go
- adapters/vastbidder/etree_parser_test.go
- go.mod
- go.sum
> OTT-1824-P4: updated etree library to return trimmed text

- adapters/pubmatic/pubmatic.go
- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
> UOE:11841,UOE:11842 reading bidfloor and bidfloorcur from either request or adunitconfig

- go.mod
- go.sum
- openrtb_ext/fastxml_ow.go
> update dependencies and add XML data retrieval function

- adapters/criteo/params_test.go
- modules/pubmatic/openwrap/adapters/bidders.go
- modules/pubmatic/openwrap/adapters/bidders_test.go
- openrtb_ext/imp_criteo.go
- static/bidder-params/criteo.json
> Criteo: Add pubid/uid fields in the configuration (#4132)

- endpoints/events/vtrack_ow.go
- exchange/exchange_ow.go
- go.mod
- go.sum
- openrtb_ext/fastxml_ow.go
> UOE-11752-P1: Fixing mismatch rates of vastunwrapping

- go.mod
- go.sum
> UOE-11752-P2: adding time stats in unwrap testcases

- go.mod
- go.sum
> UOE-11752-P1: updating vastunwrap commit id

- go.mod
- go.sum
> UOE-11752-P1: updating etreestats.response_time for unwrapping

- exchange/events_ow.go
- exchange/exchange_ow.go
- exchange/exchange_ow_test.go
- go.mod
- go.sum
- metrics/config/metrics_ow.go
- metrics/go_metrics_ow.go
- metrics/metrics_mock_ow.go
- metrics/metrics_ow.go
- metrics/prometheus/prometheus_ow.go
- metrics/prometheus/prometheus_ow_test.go
> UOE-11752-P1: updating vastunwrap metrics time stats

- go.mod
- go.sum
- modules/pubmatic/openwrap/config/config.go
- modules/pubmatic/openwrap/openwrap.go
> UOE-12049: Call the VastAdTagURI using the SSL certificate in the vastunwrap repository

- go.mod
- go.sum
- modules/pubmatic/openwrap/openwrap.go
> UOE-12049-P1: Adding support for empty certificates

- .devcontainer/devcontainer.json
- .github/workflows/adapter-code-coverage.yml
- .github/workflows/validate-merge.yml
- Dockerfile
> Go upgrade

- go.mod
- go.sum
- modules/pubmatic/openwrap/openwrap.go
> UOE-12179: Add support to pass ssl_key in vastunwrap config

- modules/pubmatic/openwrap/models/constants.go
> UOE-12321-p1: Add EndpointInvalid constant for invalid endpoint type

- modules/pubmatic/openwrap/applovinmax.go
- modules/pubmatic/openwrap/applovinmax_test.go
- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/country_filtering.go
- modules/pubmatic/openwrap/country_filtering_test.go
- modules/pubmatic/openwrap/sdk/googlesdk/request.go
- modules/pubmatic/openwrap/sdk/googlesdk/request_test.go
Reverts PubMatic-OpenWrap/prebid-server#1076
> Revert UOE-12403: Add IP field support and enable country filtering for GoogleSDK integration

- adapters/nativo/nativo.go
- adapters/nativo/nativotest/exemplary/banner-app.json
- adapters/nativo/nativotest/exemplary/banner-web.json
- adapters/nativo/nativotest/exemplary/native-app.json
- adapters/nativo/nativotest/exemplary/native-web.json
- adapters/nativo/nativotest/exemplary/video-app.json
- adapters/nativo/nativotest/exemplary/video-web.json
- modules/pubmatic/openwrap/adapters/bidders.go
- modules/pubmatic/openwrap/adapters/bidders_test.go
- modules/pubmatic/openwrap/adapters/builder.go
- openrtb_ext/imp_nativo.go
- static/bidder-params/nativo.json
>  UOE-12550: Adding placementid support for Nativo 
