- adapters/pubmatic/pubmatic.go
- openrtb_ext/request.go
added request specific composite object to prebid request extension to be passed on the adapters. modified pubmatic adapter to retrieve and use it
> UOE-3793  Add a new request specific object to request extension

- adapters/pubmatic/pubmatic.go
- exchange/utils.go
- openrtb_ext/request.go
added an ext object to prebid ext to store bidder specific key, value objects. Parse the generic request to filter and allocate bidder parameter to that bidder request only. retrieve pubmatic specific param and send it via header to pubmatic adserver
> changes to add bidder specific parameters to the prebid ext

- exchange/exchange.go
- exchange/exchange_test.go
- pbsmetrics/config/metrics.go
- pbsmetrics/go_metrics.go
- pbsmetrics/metrics.go
- pbsmetrics/metrics_mock.go
- pbsmetrics/prometheus/prometheus.go
- pbsmetrics/prometheus/prometheus_test.go
- router/router.go
**For OTT-45 - Using this branch to merge it to OTT-9 (Feature branch of Deal Priortization)**
-  Closed PR-https://github.com/PubMatic-OpenWrap/prebid-server/pull/79 - It was containing CI branch downmerged code. 
-  Closed PR - https://github.com/PubMatic-OpenWrap/prebid-server/pull/83 - It was created directly against CI branch. Actaully OTT-45 should following this merge path : OTT-45 -> OTT-9 -> CI
1. This branch contains changes for https://github.com/PubMatic-OpenWrap/prebid-server/pull/79 , excluding the CI branch downmerge
2. Code review for OTT-45 is already done on 21 Oct 2020 12:30 PM. comments w.r.t. https://github.com/PubMatic-OpenWrap/prebid-server/pull/79 are already addressed here and are as follows
3. Ref (https://github.com/PubMatic-OpenWrap/prebid-server/pull/79#issue-5 …
> OTT-45: Added logger and prometheus metrics to capture bid.id collisions

- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
@pm-viral-vala : Please review and approve
Added functionality to prefer using video ad duration returned by the bidder.
If it is 0 or any error is occurred in determining it then impression-level max duration value
will be used.
> OTT-67: Added functionality to prefer using actual video ad duration 

- endpoints/openrtb2/ctv/constant/constant.go
- exchange/exchange.go
- pbsmetrics/config/metrics.go
- pbsmetrics/go_metrics.go
- pbsmetrics/metrics.go
- pbsmetrics/metrics_mock.go
- pbsmetrics/prometheus/prometheus.go
- pbsmetrics/prometheus/prometheus_test.go
1. Copy of  PR-https://github.com/PubMatic-OpenWrap/prebid-server/pull/92 (Master Merge)
2. PR-https://github.com/PubMatic-OpenWrap/prebid-server/pull/92 already reviewed and approved
3. Approval - https://github.com/PubMatic-OpenWrap/prebid-server/pull/92#pullrequestreview-555144735 
4. NOTE - endpoints/openrtb2/ctv/constant/constant.go  - Though this is not part of OTT-71, allowing this change to be pushed on CI branch.
Reason:
Expected value for CombinationGeneratorV1 is comb_gen_v1
Master branch already having comb_gen_v1 - https://github.com/PubMatic-OpenWrap/prebid-server/blob/master/endpoints/openrtb2/ctv/constant/constant.go
Looks like ci branch is not in sync with master
> OTT-71: (CI) Add stats collecting information around the actual Ad duration

- adapters/vastbidder/tagbidder_test.go
- adapters/vastbidder/vast_tag_response_handler.go
- exchange/adapter_map.go
- exchange/exchange.go
- exchange/exchange_test.go
Filter out Ads based on domains provided in the request
@pm-viral-vala and /  @PubMatic-OpenWrap : Following review comments are addressed
1. Renamed `adjustDomain` to `noarmalizeDomain`
2. normalizeDomain will now check, if the input is publicsuffix (without icann). If it is publicsuffix, error will be returned with empty value
3. Added few more unit tests.
> OTT-101: Added exchange.applyAdvertiserBlocking and unit tests around it

- endpoints/events/vtrack.go
- endpoints/events/vtrack_test.go
- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
@pm-viral-vala : please review and approve.
1. Add **au** parameter in OpenWrap video event tracker URL 
2. **au** parameter will log the Publisher's Ad Tag Id (using imp.tagId) from the respective impression object.
3. Only for Video Creative(for any endpoint in OW).
4. Add **bidid** parameter in OpenWrap video event tracker URL. this parameter will contain value present in bid.ID field
5. **NOTE**:  In the case of CTV/Ad Pod response, **bidid** value would be id generated by CTV auction module. Hence, it may not be the same as bid.ID
6. **advertiser_id** : Pass only index 0 value from bid.ADomain array. Instead of sending all array values.
7. **advertiser_id**: Ensure that only the domain is getting passed as a part of this parameter. For example, if bid.ADomain = …
> OTT-174: Added bid ID , Ad Unit as tracking parameters and ADomain handling change

- endpoints/events/vtrack.go
- endpoints/events/vtrack_test.go
OTT-192: Ensure sURL (Event Tracker) and orig (OW Logger) parameter values are consistent
> OTT-192: Ensure sURL (Event Tracker) and orig (OW Logger) parameter values are consistent

- exchange/exchange.go
- exchange/exchange_test.go
1) Skip dedupe check
2) Bidcollision detector
> OTT-216: add all SupportDeal features

- analytics/event.go
- endpoints/events/event.go
- endpoints/events/event_test.go
1) Adding new value "vast" for t parameter and new parameter type
2) Values for vtype - [start, firstQuartile, midPoint, thirdQuartile, complete]
> OTT-422: Adding support for eventType=vast in analytic endpoint

- adapters/bidder.go
- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- exchange/bidder.go
(cherry picked from https://github.com/PubMatic-OpenWrap/prebid-server/pull/259)
> UOE-7051: Fix pubmatic aliases buyid targeting key

- endpoints/events/vtrack_ow_test.go
- endpoints/openrtb2/ctv_auction.go
- floors/enforce.go
> OTT-356: Setting WB=1 for adpod bids for new generate bid id feature

- exchange/exchange.go
- floors/enforce.go
- openrtb_ext/response.go
To know about floor rule selection and imp.bidfloor value, Updatedrequest field is added into debug response when debug=1 and floors are enabled in request.
> OTT-478: Added updatedrequest in debug log response to know about floor rule selection 

- openrtb_ext/user.go
One of our Bidder Partner needed req.user.ext.data to pass user related information, adding Data field enables to pass the data regarding user with UserExt object format
> UOE-7958: Added Data field in ExtUser

- go.sum
Updated go.sum as per tag changes for mxm-cherry
> UOE-8097: updated go.sum 

- floors/floors.go
- floors/rule.go
- floors/rule_test.go
- openrtb_ext/floors.go
> OTT-782-Prebid: As prebid server floors user, use imp[].ext.prebid.floors.floorMin to set floors values for each impression

- floors/fetcher.go
- floors/fetcher_test.go
- floors/floors.go
- floors/floors_test.go
1. Floor JSON with an invalid skip rate is being accepted
2. Application fails to start when the max_age_sec value in the config is 600.
3. Dynamically fetched floor does not expire with max-age-sec provided in config
4. Error message being printed when max-age-sec is not present in the header
5. floors.floorendpoint.url is not passed to the prebid server when floors JSON is successfully fetched.
6. Immediate refetch is not happing if the period is set to 5min
> OTT-827-828 :: Fixed issues related to dynamic fetch

- analytics/core_ow.go
- endpoints/openrtb2/ctv/response/adpod_generator.go
- endpoints/openrtb2/ctv/response/adpod_generator_test.go
- exchange/floors.go
OTT-786: Reverting (set bid status wrt to highest(winning) combination)
> OTT-786: Reverting (set bid status wrt to highest(winning) combination)

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- openrtb_ext/imp_pubmatic.go
Passing BidviewabilityScore, when present, to translator impression extension and exclusive to pubmatic only
> UOE-8566: Pass Bidviewability-data to pubmatic adserver

- endpoints/events/vtrack_ow.go
- endpoints/events/vtrack_ow_test.go
85% improvement in cpu usage and 25% improvement in memory usage of `GetVideoEventTracking()`
```
// Original:
// Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^BenchmarkGetVideoEventTracking$ github.com/PubMatic-OpenWrap/prebid-server/endpoints/events
// goos: linux
// goarch: arm64
// pkg: github.com/PubMatic-OpenWrap/prebid-server/endpoints/events
// BenchmarkGetVideoEventTracking-8   	   19048	     78882 ns/op	   31590 B/op	     128 allocs/op
// BenchmarkGetVideoEventTracking-8   	   27333	     40491 ns/op	   31589 B/op	     128 allocs/op
// BenchmarkGetVideoEventTracking-8   	   28392	     45111 ns/op	   31586 B/op	     128 allocs/op
// BenchmarkGetVideoEventTracking-8   	   18160	     83581 ns/op	   31585 B/op	     128 allocs/op
// BenchmarkGetVideoEventTracking-8 …
```
> Optimise get video event tracking for minimal memory allocs

- endpoints/openrtb2/ctv/impressions/by_duration_range_test.go
- endpoints/openrtb2/ctv/impressions/by_duration_ranges.go
- endpoints/openrtb2/ctv/impressions/impressions.go
- endpoints/openrtb2/ctv/impressions/impressions_test.go
- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
- openrtb_ext/adpod.go
- openrtb_ext/adpod_test.go
This pr has change to rename adpod related configurations
1) adPodsEnabled becomes adPodConfiguration
2) videoLengths  becomes videoAdDuration
3) videoLengthMatching  becomes videoAdDurationMatching
> OTT-914: Renaming Adpod Configurations

- endpoints/openrtb2/amp_auction_test.go
- endpoints/openrtb2/auction_test.go
- endpoints/openrtb2/video_auction_test.go
- exchange/bidder_test.go
- version/xprebidheader.go
- version/xprebidheader_test.go
> UOE-8535: set pbs-go to owpbs-go in xprebidheader

- exchange/exchange_test.go
- openrtb_ext/deal_tier.go
- openrtb_ext/deal_tier_test.go
> UOE-8837: handle unmarshal error for imp.ext.{bidder} when imp.ext.tid is present

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- openrtb_ext/imp_pubmatic.go
[UOE-8902] - As per Changes in the Bidviewability structure, removing the adapter level checks for viewability data
> UOE-8988(Bug fix): Removing restriction for bidviewability Datatype check

- adapters/pubmatic/pubmatic.go
- adapters/pubmatic/pubmatic_test.go
- openrtb_ext/imp_pubmatic.go
[UOE-8902] - As per Changes in the Bidviewability structure, removing the adapter level checks for viewability data
> UOE-8988: update bidviewability datatype to generic

- endpoints/openrtb2/auction.go
- endpoints/openrtb2/ctv_auction.go
> OTT-970: As a OpenWrap Server user, should be able to pass VAST unwrapper enable flag to prebid server

- endpoints/openrtb2/auction.go
- endpoints/openrtb2/auction_test.go
@ashishshinde-pubm : Please check my review comments.
1. I could see similar issue in https://github.com/prebid/prebid-server/blob/961bb8357202142b9b5f4ab6ebe5c71bdd20a356/endpoints/openrtb2/auction.go#L2006  - Let us see if we can fix this to in prebid-pr / in OW if we are using that function. Even that can cause panic
> OTT-1262: Fix panic observed for hybrid endpoint when site object is nil

- modules/pubmatic/openwrap/database/mysql/adunit_config.go
- modules/pubmatic/openwrap/database/mysql/adunit_config_test.go
> UOE-9443: handle missing 'default' adunitconfig

- floors/enforce.go
- floors/enforce_test.go
- floors/floors.go
bidadjustment factor: 0.9
original bidfloor: 4 USD
bidfloor in partner request 4/0.9 = 4.444444444444445
bid returned by partner : 4.44 USD
final bid price : 4.44-10% = 3.996 USD
in above scenario bid was getting rejected since bid price 3.99 is less than bidfloor 4 even when bidder returned bid which is equal to the bidfloor in request.
> OTT-1254: Added changes for considering 2 decimal points precision loss during bid rejection due to floors

- modules/pubmatic/openwrap/database/mysql/adunit_config.go
- modules/pubmatic/openwrap/database/mysql/adunit_config_test.go
> DCOPS-1343: Handle legacy invalid profiles

- modules/pubmatic/openwrap/database/mysql/adunit_config.go
- modules/pubmatic/openwrap/database/mysql/adunit_config_test.go
> OTT-1297: fix: do not log error stats for profiles w/o adunitconfig

- modules/pubmatic/openwrap/metrics/stats/client.go
Code changes to print the stats metrics if loglevel is debug.
> OTT-1377: Print stats to be sent to stats-server

- exchange/bidder.go
- exchange/exchange.go
- exchange/exchange_ow.go
- exchange/exchange_ow_test.go
- metrics/config/metrics.go
- metrics/config/metrics_ow.go
- metrics/go_metrics_ow.go
- metrics/metrics.go
- metrics/metrics_mock_ow.go
- metrics/metrics_ow.go
- metrics/prometheus/prometheus.go
- metrics/prometheus/prometheus_ow.go
- metrics/prometheus/prometheus_ow_test.go
> OTT-1319: add prometheus stats to count number of bids with vast unwrapped

- hooks/plan.go
> OTT-1410:Removed warning message when module is not enabled

- endpoints/openrtb2/auction.go
- endpoints/openrtb2/auction_test.go
- endpoints/openrtb2/sample-requests/valid-whole/exemplary/all-ext-case-insensitive.json
- endpoints/openrtb2/sample-requests/valid-whole/exemplary/simple-case-insensitive.json
- endpoints/openrtb2/sample-requests/valid-whole/exemplary/simple.json
- exchange/exchange_test.go
- exchange/utils.go
Making changes for the NextMillennium bidder. The biddercode of the bidder is nextMillennium as per [documentation](https://docs.prebid.org/dev-docs/bidders/nextMillennium.html) but the prebid is expecting bidder code nextmillennium. prebid fixed case insensitive comparison in auction request issue in : https://github.com/prebid/prebid-server/pull/3113/files.
Which will resolve this problem.
cherry picking this fix for quick resolution instead of upgrade.
Ticket: https://inside.pubmatic.com:9443/jira/browse/UOE-9599
> UOE-9599: make case insensitive comparison in auction request (#3113)

- modules/pubmatic/openwrap/utils/bid.go
- modules/pubmatic/openwrap/utils/bid_test.go
> Fix: Single colon in BidId causing inconsistent split

- modules/pubmatic/vastunwrap/entryhook.go
- modules/pubmatic/vastunwrap/hook_raw_bidder_response.go
- modules/pubmatic/vastunwrap/hook_raw_bidder_response_test.go
- modules/pubmatic/vastunwrap/models/request.go
- modules/pubmatic/vastunwrap/module.go
- modules/pubmatic/vastunwrap/module_test.go
- modules/pubmatic/vastunwrap/stats/metrics.go
- modules/pubmatic/vastunwrap/stats/metrics_test.go
- modules/pubmatic/vastunwrap/stats/mock/mock.go
- modules/pubmatic/vastunwrap/unwrap_service.go
- modules/pubmatic/vastunwrap/unwrap_service_test.go
> OTT-1431: Added publisher level stats for vast-wrapper count and response time

- modules/pubmatic/vastunwrap/entryhook.go
- modules/pubmatic/vastunwrap/entryhook_test.go
- modules/pubmatic/vastunwrap/module_test.go
> OTT-1441: Moved random number generation  from VAST un-wrap module to OW server 

- modules/pubmatic/openwrap/models/openwrap.go
[Fixed marshling error when we send trace=verbose in request.](https://github.com/PubMatic-OpenWrap/prebid-server/pull/665)
> UOE-9681: Fix trace marshal error

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/util.go
- modules/pubmatic/openwrap/util_test.go
- When we enable the hook and send the traffic through the module then in-correct UA is being send to the wtracker server.
- It is expected that high priority should be given to the "device.UA" over request-header, but in case of modular flow we only considers the request-header.
- Root-cause :
rCtx is **pass-by-value** to function getDevicePlatform and getDevicePlatform attempts to modify it inside the function but reciever never get the modified value.
> OTT-1541: req.device.UA should get higher priority over UA from request-header while sending owlogger to wtracker-server

- modules/pubmatic/openwrap/adpod/adpod.go
- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/logger_test.go
> OTT-1654: Impression are getting formed for inline hb when nothing is in range

- go.mod
- go.sum
> OTT-1650: Update vast unwrap commit id in go.mod

- modules/pubmatic/openwrap/database/mysql/partner_config.go
- modules/pubmatic/openwrap/database/mysql/partner_config_test.go
> UOE-10050: Fetch vendorId for VastBidder from db table

- endpoints/openrtb2/ctv_auction.go
- endpoints/openrtb2/ctv_auction_test.go
Refer - https://inside.pubmatic.com:9443/jira/browse/OTT-1722 for more details
> OTT-1722: Fix panic when VAST element is missing in video creative for CTV adpod request

- endpoints/openrtb2/ctv/adpod/dynamic_adpod.go
- endpoints/openrtb2/ctv/adpod/structured_adpod.go
- endpoints/openrtb2/ctv/adpod/structured_adpod_test.go
- endpoints/openrtb2/ctv/adpod/util.go
- endpoints/openrtb2/ctv/adpod/util_test.go
- endpoints/openrtb2/ctv_auction.go
- openrtb_ext/openwrap.go
Sample exclusion config:
```
{
"ext": {
"adpod": {
"exclusion": {
"iabcategory": [
"pod1",
"pod2"
],
"advertiserdomain": [
"pod1"
]
}
}
}
} 
```
> OTT-1738 :: provide exclusion config to adpod through request ext

- modules/pubmatic/openwrap/device.go
- modules/pubmatic/openwrap/device_test.go
> OTT-1982: Honor IFA over session_id if when ifa_type is absent

- modules/pubmatic/openwrap/beforevalidationhook.go
> Fixed panic when connectionType is not available in request

- adapters/vastbidder/etree_parser.go
- adapters/vastbidder/etree_parser_test.go
- go.mod
- go.sum
- modules/pubmatic/openwrap/metrics/config/multimetrics.go
- modules/pubmatic/openwrap/metrics/config/multimetrics_test.go
- modules/pubmatic/openwrap/metrics/metrics.go
- modules/pubmatic/openwrap/metrics/mock/mock.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus.go
- modules/pubmatic/openwrap/metrics/prometheus/prometheus_test.go
- modules/pubmatic/openwrap/metrics/stats/tcp_stats.go
> RE-3735: Release 17th Sept 2024

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/models/constants.go
- modules/pubmatic/openwrap/models/openwrap.go
**func extractItunesIdFromAppStoreUrl benchmarking**
**Wthout Regex:**
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
BenchmarkFindTrailingDigits-8            5594328               201.0 ns/op            48 B/op          9 allocs/op
BenchmarkFindTrailingDigits-8            5764165               204.2 ns/op            48 B/op          9 allocs/op
BenchmarkFindTrailingDigits-8            5838740               205.0 ns/op            48 B/op          9 allocs/op
BenchmarkFindTrailingDigits-8            5772484               198.7 ns/op            48 B/op          9 allocs/op
BenchmarkFindTrailingDigits-8            5722549               205.3 ns/op            48 B/op          9 allocs/op
BenchmarkFindTrailingDigits-8            5892768               201.9 ns/op            48 B/op …
> UOE-11183: consume StoreURL from New portal UI and forward appstoreurl and appsource for applovinmax

- modules/pubmatic/openwrap/applovinmax.go
- modules/pubmatic/openwrap/applovinmax_test.go
UOE-11360: Use sessionduration and impdepth from signal only, ignore if present in request user extension
> UOE-11360: Use sessionduration and impdepth from signal only, ignore if present in request user extension

- adapters/vastbidder/etree_parser_test.go
- modules/pubmatic/openwrap/tracker/video.go
- modules/pubmatic/openwrap/tracker/video_test.go
> UOE-11484: fixing invalid vast xml for spaces in pricing node

- adapters/vastbidder/etree_parser.go
- adapters/vastbidder/etree_parser_test.go
- adapters/vastbidder/fastxml_parser.go
- adapters/vastbidder/fastxml_parser_test.go
Currently, when retrieving pricing details, we are checking the /Extensions/Extension/Price and Pricing attributes in the VAST XML. We need to also support /Extensions/Extension/Pricing to handle all cases where the pricing node might be present. The priority should be: first, check for the root-level Pricing attribute, then /Extensions/Extension/Pricing, and finally /Extensions/Extension/Price, without depending on any specific VAST version.
> UOE-11628: Fix: Invalid Price value added in VAST version more than 3.0

- scripts/upgrade-pbs.sh
> Refactor upgrade script to accept custom workspace path as an argument, defaulting to "GOPATH/src"

- .github/workflows/adapter-code-coverage.yml
- .github/workflows/validate-merge.yml
- .github/workflows/validate.yml
- go.mod
> Bump Go version from 1.21 to 1.23 in go.mod

- modules/pubmatic/openwrap/beforevalidationhook.go
- modules/pubmatic/openwrap/beforevalidationhook_test.go
- modules/pubmatic/openwrap/models/openwrap.go
- modules/pubmatic/openwrap/sdk/googlesdk/request.go
- modules/pubmatic/openwrap/sdk/googlesdk/request_test.go
Addressed below points in the PR
1. Add support of setting app store id in `bid.imp.ext.skadn.sourceapp`
2. Read ad_unit_mapping iteratively for Openwrap related key-values instead of reading the first element from the array.
3. For reading SDK signal for iOS, read for key = GADMediationAdapterPubMatic 
4. Fix: Device from signal is not getting updated if its absent in admob request
> UOE-12335: Add support of setting app store id in bid.imp.ext.skadn.sourceapp

- modules/pubmatic/openwrap/sdk/googlesdk/request.go
- modules/pubmatic/openwrap/sdk/googlesdk/request_test.go
> UOE-12574:[GoogleSDK]: Consume imp.ext.skadn.skadnetids from signal data
